language: node_js
node_js: 8
script:
- npm test
branches:
  only:
  - master
deploy:
  provider: npm
  email: billing.media@schibsted.media
  on:
    branch: master
    node: '8'
  api_key:
    secure: 1mPekiwM4kXaFa9D756bVsk4JooXhn3Lu9wqnwbdKhHzmgIz2Mbgq2AvIraimFwYhzY3+3Fd2YoMM73XMeFwRBF5n5+S/BFB48PZnPyFI9U4EeB+5w5d0xE97pzymk6JJfYQ8WRiUF1WUlA0CSsnn/1OkUYB0a2HV540RPaUKWieiend+b1svkjMEQHIei85VkaGl6o0GHF0uPcirUXojZCwpgCloL5GTIZGfsYgruR/24pBIwi0ctvwdtIYOW/2/yxJFOalQ/4jl2z70PAbPwNVjaFFANptaCEEVzLxtxPenyzjaW7xjRsueG4FUEDlJg7mryeez0M6cZJEXspjpxUXSamt/DCSCdMRKSkeSs55nasX91aZhCtk6fIZ/JzjSHJs5yKg8Y7cbU0mVWE0VDnZaZLaJ2TSwCqxovAgcHm0daHBYjhlymwcTNYDMvmaKl0unUv7gnWWqPtWKPpq4+fJnzEENuOwu+lMHgw0p2ncJ8BbkNQQGl6157E8laBDf5ftqJMPQ2f2mKBhUNm6dwYSrrxvNM6ApUNFxaTMq7H2Eh3meb7qQAK3UKB54LHZuHmoVoBehEDSz4LTHwKX4uU/QQGrrxWoEFEXX6gdEqsVUy76iV025bQGD8BLHSHLIqT8VIehnr1mgn0Zxr6WkWle51dE7eSDAuOm+tiAqOc=
