language: node_js
node_js: 8
before_install:
- npm i -g npm@6
script:
- npm test
- npm run lint
- npm audit
branches:
  only:
  - master
deploy:
  provider: npm
  email: billing.media@schibsted.media
  on:
    branch: master
    node: '8'
  api_key:
    secure: AUFb7IYAuOncq9KwH6iQLn3nAnbewV9RYQ+L96jIB4G0jOyj0SNSCgaOlln0ONm1zOFu4yyZxRuFBhzAEo8zD0Z5zxPkos4u2FFeGacrvrVKGosKtqxxNQNkPa8r5ihXF90vL3H2ARJTlWE8qN5dGYmzvJB9R5DiWUGD0OCnLGwoc/ZmynTy3Vg/YrD/HHG4DHlaGokKVNjPVmuVZmp9+QbkIqi7+3Tsl/MXnjxxue8T2/n8uDTyvK9eOsZ3P8YT/sSqyALj1+2Yu6M+Ogq+dtcsZlSjE9ALXE5SfViY32uygu77L2yuLi0Gh1fRG2qimoMw24yyXSSQ3MynKBR8WiZH2TGtJEA6OpsHZJ6y9eSFX4jRPqBR9LArNYR/S01yMA3IoAlJQFfTfylwqaWMDxVXLrhvwM7dUuwUAA+mcHle1owJWclkTHIZ7TyAg2X0AL2eLziTMNlXv8NMmceKzBRd4Mci+ygkwik02AJ7+6pjscwQFr/GAAbAfSIx22UtmTP49hHvkIw7cn4ErZgKh8we8Lq/9StZIbWPVPri1XRL4XWmuT8QnNVyyCOZUVi0GltkoqaJKPVn5T7FWhr58He43WSwaCfBkBgvbzAQfqGy9e/lLxdUYv5SEto08WWelOoHSyedEj9oSILWTQggVb/YNTAbUmxruADj2sPcB3o=
