language: node_js
node_js: 8
script:
- npm test
branches:
  only:
  - master
deploy:
  provider: npm
  email: billing.media@schibsted.media
  on:
    branch: master
    node: '8'
  api_key:
    secure: eVw7kB77dC4CLAPg2vvxkX8wIncUg5FiX2vRTP+yBD07OeLyQ3PfdI7J7pcqfMY8CjVWPARUSM8iQ83r2iWKLbhaakBSQ8KLmoTgcCwBDqPSZt6cTCQyRUhMm1SjFmE81hnkPCfSHPgq76udwwk+UfwkWHtK/fof52DczrHgyMzgVy1CBDubKQcaZhuScNa85iyxNd7iA/TjdlWCSVKAYwaCrx3ZDlHrWDYwvgta3aGGE7z62TaJxYIENgqfl8bODxJT2HFPSJyz7IcADbKKo9cVdR/+AfdtjFvp9rQCz+VIMEc+h17Mh6Pz5LU2r4HRZjjXUSbCuFOK3r4WFyqAwsGm3IVNnOYBmz9NPyEq9ASmWOzpI1V0mAbsLOEPh3dfH50ZHtgnj0daRGdlwYWLv2ZuTVLKp1L56cI7u3w81458ci1n6LU+RHjYw3az4CHDhD8e/0SBn9nZ52tqHGD7gp5S22COrFQLn3ddQ2ELw1MoufBvGhlkM2Kcdl003o6XPJa/zVX6g4Ba++TG1sOsPY9a92ScgTFCGNn5jwUxAg8aiJ703S9YPxOup/yJLVhZJ7MNMfA41Z+AC6rH+FE6nWYXcpmkYBwGD0nEKIjD75IDh019dAVVRqC3fitnz11JUDo0sP1VEefHS87llVk38BqHcTNhZHckqxeTrwAY7+k=
